version: '2.1'
services:
  db:
    image: alekseypauls/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 3s
      retries: 5
  web:
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    build: .
    command: bash -c "./start.sh"
    volumes:
      - .:/code
    ports:
      - "5000:5000"